require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'tmp/**/*'


Style/Documentation:
  Enabled: false
