default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # for docker-compose
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 15432 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: jp_development

test:
  <<: *default
  database: jp_test

production:
  <<: *default
  database: jp_production
  username: jp
  password: <%= ENV["JP_DATABASE_PASSWORD"] %>
