default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # for docker-compose
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 15432 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: jp_development

test:
  <<: *default
  database: jp_test

production:
  <<: *default
  database: <%= ENV["PRODUCTION_DB_NAME"] %>
  username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  password: <%= Rails.application.credentials.gcp&.fetch(:db_password) %>
  host: "<%= ENV.fetch('DB_SOCKET_DIR', '/cloudsql') %>/<%= ENV['CLOUD_SQL_CONNECTION_NAME'] %>"
  port: 5432

